### ISSUE TITLE
slide's step parameter is broken

### ISSUE THREAD

**Issue by dcghub** [symmetryinvestments/concurrency#56]
`slide(3, 3)` returns 

`[[1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 2, 6], [1, 2, 7], [1, 2, 8], [1, 2, 9],....`

instead of 

`[[1, 2, 3], [3, 4, 5], [6, 7, 8]...`

**Comment by dcghub** [comment]
Also, step shouldn't be allowed to be zero

**Comment by skoppe** [comment]
Fixed in https://github.com/symmetryinvestments/concurrency/commit/c85403b748b3a3ddc8750ceed8cf6143ee4944d6 and https://github.com/symmetryinvestments/concurrency/commit/6da4e909651b010decaa8622adf2220405dabd7c

**Comment by skoppe** [comment]
released https://github.com/symmetryinvestments/concurrency/releases/tag/v4.8.0
